#!/bin/sh
#
# aura - an imitation of aurafetch
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright.

echo

# TODO: use fetchutils to get kernel
kernel=$(uname -r)
kernel=${kernel%-*}

blocks=$(printf '\033[0m\033[31m ▲\033[32m ▼\033[33m ▲\033[34m ▼\033[35m ▲\033[36m ▼\033[37m ▲\033[0m')

reset=$(printf '\033[0m')
color1=$(printf '\033[1;31m')

format_info() {
    printf '%s%-10s %s%10s\n' "$color1" "$1:" \
        "$reset" "$2"
}

format_info user   "${USER}"
format_info os     "$(../src/os.sh '$id')"
format_info kern   "${kernel}"
format_info ed     "${EDITOR:-$VISUAL}"
format_info sh     "${SHELL##*/}"
format_info pkgs   "$(../src/pkgs.sh)"

# TODO: use fetchutils for temrminal
format_info term   "${TERM%%-*}"

echo
echo "   $blocks"

echo
