#!/bin/sh
#
# simple - simple fetch script built on fetchutils
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

echo "
    ___     ${USER}@$(hostname)
   (.. |    os: $(../src/os.sh)
   (<> |    shell: ${SHELL##*/}
  / __  \   pkgs: $(../src/pkgs.sh '$pkgs_total')
 ( /  \ /|  uptime: $(../src/upt.sh)
_/\ __)/_)  memory: $(../src/mem.sh)
\/_____\/   kernel: $(uname -r)
" 2>/dev/null
