#!/bin/sh
#
# mem - get memory usage information
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

[ -z "$1" ] && set -- '${gb_used}G / ${gb_total}G'

while IFS=: read -r set data; do
    data="${data%%kB}"

    case "$set" in
        MemTotal)
            kb_used=$((kb_used+=data))
            kb_total=$((kb_total=data))
        ;;

        Shmem)
            kb_used=$((kb_used+=data))
        ;;

        MemFree|Buffers|Cached|SReclaimable)
            kb_used=$((kb_used-=data))
        ;;
    esac
done < /proc/meminfo

b_used=$((kb_used*1024))
b_total=$((kb_total*1024))
mb_used=$((kb_used/1024))
mb_total=$((kb_total/1024))
gb_used=$((mb_used/1024))
gb_total=$((mb_total/1024))

eval echo "$1"
