#!/bin/sh
#
# pkgs - get number of pkgs
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

command=
[ -z "$1" ] && set -- "$(os)"

case "$1" in
    void)
        command="xbps-query -l"
    ;;
esac

$command | wc -l
