#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get CPU temperature
#

[ -z "$1" ] && set -- '${c}°C'

c=

case $(uname) in
    OpenBSD)
        c=$(sysctl -n hw.sensors.cpu0.temp0)
        c="${c%.*}"
    ;;
    Linux)
        read -r c </sys/class/thermal/thermal_zone0/temp
        c="${c%???}"
    ;;
esac

eval echo "$1"
