#!/bin/sh
#
# upt - get uptime on hosts
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

[ -z "$1" ] && set -- '${d} ${h} ${m}' 'd' 'h' 'm' 's'
[ -f /proc/uptime ] || exit 1

s=$(cat /proc/uptime)
s=${s%%.*}

d=$((s/86400))
h=$((s/3600%24))
m=$((s/60%60))

[ $d = 0 ] || d="${d}${2}"
[ $h = 0 ] || h="${h}${3}"
[ $m = 0 ] || m="${m}${4}"
[ $s = 0 ] || s="${s}${5}"

eval echo "$1"
